force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <label>Bid</label>
    <nameField>
        <label>Bid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bid__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Bid__c.field-meta.xml
<CustomField>
    <fullName>Bid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bid</label>
    <referenceTo>Bid__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityService.cls
public class OpportunityService {

    public static void createDefaultSection(List<Bid__c> newItems){
        List<Section__c> tenpSectionList = new List<Section__c>();
        Section__c tempSection = new Section__c();
        for (Bid__c bid : newItems) {
            tempSection.bid__c = bid.Id;
            tempSection.Name = 'Default';
            tenpSectionList.add(tempSection);
            tempSection = new Section__c();
        }
        try {
            if(tenpSectionList.size() > 0){
                insert tenpSectionList;
            }
        }catch(Exception ex){
            system.debug('Error on creating default sections: ' + ex.getMessage());
        }
        
	}
    public static void createDefaultBid(Map<Id, Opportunity> newItems){
        List<Bid__c> tempBidList = new List<Bid__c>();
        Bid__c tempBid = new Bid__c();
        for (Opportunity opp : newItems.values()){
            tempBid.Name = 'Default ' + opp.Name;
            tempBid.Opportunity__c = opp.Id;
            tempBidList.add(tempBid);
            tempBid = new Bid__c();
        }
        try {
            if(tempBidList.size() > 0){
                insert tempBidList;
                OpportunityService.createDefaultSection(tempBidList);
            }
        }catch(Exception ex){
            system.debug('Error on creating default bid: ' + ex.getMessage());
        }
	}
    
}