force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <label>Bid</label>
    <nameField>
        <label>Bid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bid__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bid__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Responding</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linked_Tag__c/Linked_Tag__c.object-meta.xml
<CustomObject>
    <label>Linked Tag</label>
    <nameField>
        <displayFormat>LT-{00000}</displayFormat>
        <label>Linked Tag ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Tag__c/fields/Linked_Requirement_to_Tags__c.field-meta.xml
<CustomField>
    <fullName>Linked_Requirement_to_Tags__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Requirement to Tags</label>
    <referenceTo>Requirement__c</referenceTo>
    <relationshipLabel>Linked Tags</relationshipLabel>
    <relationshipName>Linked_Tags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linked_Tag__c/fields/Linked_Response_to_Tags__c.field-meta.xml
<CustomField>
    <fullName>Linked_Response_to_Tags__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Response to Tags</label>
    <referenceTo>Response_Library__c</referenceTo>
    <relationshipLabel>Linked Tags</relationshipLabel>
    <relationshipName>Linked_Tags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linked_Tag__c/fields/Linked_Tags__c.field-meta.xml
<CustomField>
    <fullName>Linked_Tags__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Tags</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Linked Tags (Linked Tags to Library)</relationshipLabel>
    <relationshipName>Linked_Tags2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Requirement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Assign_to__c.field-meta.xml
<CustomField>
    <fullName>Assign_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Effort_Level__c.field-meta.xml
<CustomField>
    <fullName>Effort_Level__c</fullName>
    <label>Effort Level</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <label>Requirement</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response_Library__c/Response_Library__c.object-meta.xml
<CustomObject>
    <label>Response Library</label>
    <nameField>
        <displayFormat>Response - {000000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Library__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requirement</label>
    <referenceTo>Requirement__c</referenceTo>
    <relationshipLabel>Response Library</relationshipLabel>
    <relationshipName>Response_Library</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Library__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Response Library</relationshipLabel>
    <relationshipName>Response_Library</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Library__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Bid__c.field-meta.xml
<CustomField>
    <fullName>Bid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bid</label>
    <referenceTo>Bid__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SummaryController.cls
public class SummaryController {
    
    @AuraEnabled(continuation = true)    
    public static List<Section__c> getSection(String opportunityId){
         try{
             Set<Id> bidIds = new Set<Id>();
             List<Bid__c> bidList = [Select Id from Bid__c where Opportunity__c =: opportunityId];
             for(Bid__c b:bidList){
                bidIds.add(b.Id);
             }
           	 List<Section__c> sectionList = [Select Id,Name,(Select Id,Status__c,Effort_Level__c,Assign_to__c,Assign_to__r.smallPhotoURL from Requirements__r) from Section__c where Bid__c IN: bidIds ];
             return sectionList;
            
        }catch(Exception e){
            System.debug('Exception'+e);
        }
        return null;
    }
    
	@AuraEnabled(continuation = true)    
    public static Map<String,Integer> getResponseStatus(String opportunityId){
         try{
             Map<String,Integer> statusMap = new Map<String,Integer>();
             Integer In_Review = 0;
             Integer Expired = 0;
             Integer Live = 0;
             Map<Id, Section__c> sectionMap = new Map<Id, Section__c>([Select Id from Section__c where Opportunity__c =: opportunityId ]);
             List<Section__c> sectionList = [Select Id from Section__c where Opportunity__c =: opportunityId ];
             if(!sectionMap.isEmpty()){
                 List<Response_Library__c> responseList = [Select id,Status__c from Response_Library__c where Section__c IN: sectionMap.keySet()];
                 if(responseList != null && responseList.size() > 0){
                     for(Response_Library__c rl : responseList){
                         if(rl.Status__c == 'In Review'){
                             In_Review += 1;
                             statusMap.put(rl.Status__c,In_Review);
                         }
                         else if(rl.Status__c == 'Expired'){
                             In_Review += 1;
                             statusMap.put(rl.Status__c,Expired);
                         }
                         else if(rl.Status__c == 'Live'){
                             In_Review += 1;
                             statusMap.put(rl.Status__c,Live);
                         }
                     }
                     return statusMap;
                 }
                 else{
                     return null;
                 }
             	  
             }
             else{
                 return null;
             }
            
        }catch(Exception e){}
        return null;
    }

    @AuraEnabled(continuation = true)    
    public static List<Linked_Tag__c> getTags(String opportunityId){
         try{
            Set<Id> bidIds = new Set<Id>();
            Set<Id> sectionIds = new Set<Id>();
            Set<Id> requirementIds = new Set<Id>();
            List<Bid__c> bidList = [Select Id from Bid__c where Opportunity__c =: opportunityId];
            for(Bid__c b:bidList){
               bidIds.add(b.Id);
            }
            List<Section__c> sectionList = [Select Id from Section__c  where Bid__c IN: bidIds ];
            for(Section__c s: sectionList){
                sectionIds.add(s.Id);
            }
            List<Requirement__c> requirementList = [Select Id from Requirement__c  where Section__c IN: sectionIds ];
            for(Requirement__c r: requirementList){
                requirementIds.add(r.Id);
            }
            List<Linked_Tag__c> ltList = [Select Id,Linked_Tags__r.Name from Linked_Tag__c  where Linked_Requirement_to_Tags__c IN: requirementIds ];
            return ltList;
         }catch(Exception e){}
        return null;
    }
}