force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Requirement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/File_ID__c.field-meta.xml
<CustomField>
    <fullName>File_ID__c</fullName>
    <label>File ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <label>Requirement</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Requirement_Index__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Index__c</fullName>
    <label>Requirement Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Response_Index__c.field-meta.xml
<CustomField>
    <fullName>Response_Index__c</fullName>
    <label>Response Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Response_Limit_Index__c.field-meta.xml
<CustomField>
    <fullName>Response_Limit_Index__c</fullName>
    <label>Response Limit Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Score_Index__c.field-meta.xml
<CustomField>
    <fullName>Score_Index__c</fullName>
    <label>Score Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status_Index__c.field-meta.xml
<CustomField>
    <fullName>Status_Index__c</fullName>
    <label>Status Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExportFileController.cls
public with sharing class ExportFileController {
    public string fileData {get; set;} 
    public String requirementsList {get; set;} 
    public ExportFileController() {
        String fileID = System.currentPageReference().getParameters().get('fid');
        if( fileID != null ) {
            
        }
        FileWrapper fw = ResponseController.getFileBlob(fileID);//'0697Q000001WBgoQAG');
        fileData = fw.content;
        List<Requirement__c> tempRequirementsList = [Select Id, File_Id__c, Requirement_Index__c, Requirement__c, Response_Index__c, Response__c, Response_Limit_Index__c, Score_Index__c, Status_Index__c from Requirement__c where File_Id__c = '0697Q000001WBgoQAG'];
        requirementsList = JSON.serialize(tempRequirementsList);
    }
}